/**
 * Art-direction presets — 150 of them, derived from Open Design's token sets.
 *
 * GENERATED by scripts/import-design-systems.ts. Do not hand-edit: re-run the
 * script instead, or the next import silently discards the change.
 *
 * Every source system declares the same 56 tokens, already classified by layer,
 * so this is a deterministic derivation and not 150 judgement calls. The four
 * numbers in `scale` are read off the tokens rather than eyeballed:
 *
 *   density    section-y-desktop / 100     (100px is the mid-weight baseline)
 *   radius     radius-md / 12              (0 = square, >1 = soft)
 *   typeScale  (text-4xl / text-base) / 4.7 — type CONTRAST, not absolute size,
 *              because that ratio is what makes a system loud or quiet and it
 *              stays comparable across systems with different base sizes
 *   motion     motion-base / 220ms
 *
 * `atmosphere` is on when the ground is dark, measured by perceived lightness:
 * dark grounds want their glow, light ones look grubby with it.
 *
 * NAMES: Apache 2.0 licenses their files, not anybody's trademarks (§6 excludes
 * them). The values come across intact; every trademarked id carries a
 * descriptive name instead, which is also the better product — a shop owner
 * choosing a look does not know what Vercel is.
 */

import type { MoodSpec } from "./moods"

export interface DesignSystemSpec extends MoodSpec {
  id: string
  /** Shown in the picker. Never a trademark. */
  name: string
  /** Grouping for the picker, from the source manifest. */
  category: string
  /** Source ids that reduced to exactly this preset. Auditing, not display. */
  mergedFrom?: string[]
}

export const DESIGN_SYSTEMS: Record<string, DesignSystemSpec> = {
  "agentic": {
    "id": "agentic",
    "name": "Agentic",
    "category": "Themed & Unique",
    "scale": {
      "density": 0.96,
      "radius": 1,
      "typeScale": 0.94,
      "motion": 1,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#60a5fa",
      "secondary": "#8ea0b8",
      "neutral": "#f8fafc",
      "base-100": "#0b1020",
      "base-200": "#131b2f",
      "base-300": "#293653",
      "base-content": "#f8fafc",
      "success": "#22c55e",
      "warning": "#fbbf24",
      "error": "#fb7185"
    },
    "atmosphere": true,
    "rhythm": 24
  },
  "airbnb": {
    "id": "airbnb",
    "name": "Welcoming",
    "category": "E-Commerce & Retail",
    "scale": {
      "density": 0.64,
      "radius": 1.17,
      "typeScale": 0.74,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#ff385c",
      "secondary": "#6a6a6a",
      "neutral": "#222222",
      "base-100": "#ffffff",
      "base-200": "#ffffff",
      "base-300": "#dddddd",
      "base-content": "#222222",
      "success": "#008a05",
      "warning": "#c47700",
      "error": "#c13515"
    },
    "atmosphere": false,
    "rhythm": 16
  },
  "airtable": {
    "id": "airtable",
    "name": "Gridwork",
    "category": "Design & Creative",
    "scale": {
      "density": 0.96,
      "radius": 1.33,
      "typeScale": 0.64,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#1b61c9",
      "secondary": "rgba(4, 14, 32, 0.69)",
      "neutral": "#181d26",
      "base-100": "#ffffff",
      "base-200": "#ffffff",
      "base-300": "#e0e2e6",
      "base-content": "#181d26",
      "success": "#006400",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "ant": {
    "id": "ant",
    "name": "Systematic",
    "category": "Professional & Corporate",
    "scale": {
      "density": 0.96,
      "radius": 0.83,
      "typeScale": 0.85,
      "motion": 1,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#d32029",
      "secondary": "#697386",
      "neutral": "#1f1f1f",
      "base-100": "#ffffff",
      "base-200": "#f7f8fa",
      "base-300": "#d9dce3",
      "base-content": "#1f1f1f",
      "success": "#22a06b",
      "warning": "#faad14",
      "error": "#cf1322"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "apple": {
    "id": "apple",
    "name": "Precision",
    "category": "Media & Consumer",
    "scale": {
      "density": 1,
      "radius": 1,
      "typeScale": 1,
      "motion": 1,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#0071e3",
      "secondary": "#6e6e73",
      "neutral": "#1d1d1f",
      "base-100": "#ffffff",
      "base-200": "#f5f5f7",
      "base-300": "#d2d2d7",
      "base-content": "#1d1d1f",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 25
  },
  "application": {
    "id": "application",
    "name": "Application",
    "category": "Professional & Corporate",
    "scale": {
      "density": 0.88,
      "radius": 1,
      "typeScale": 0.77,
      "motion": 1,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#2563eb",
      "secondary": "#6b7689",
      "neutral": "#172033",
      "base-100": "#f6f7f9",
      "base-200": "#ffffff",
      "base-300": "#d8dee8",
      "base-content": "#172033",
      "success": "#16a34a",
      "warning": "#f59e0b",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 22
  },
  "arc": {
    "id": "arc",
    "name": "Aurora",
    "category": "Productivity & SaaS",
    "scale": {
      "density": 0.96,
      "radius": 1,
      "typeScale": 1.02,
      "motion": 1.45,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Playfair Display",
      "body": "Inter"
    },
    "colors": {
      "primary": "#ff5f5f",
      "secondary": "#8c8c93",
      "neutral": "#1a1a1f",
      "base-100": "#fdf3ec",
      "base-200": "#ffffff",
      "base-300": "#ece5db",
      "base-content": "#1a1a1f",
      "success": "#48bb78",
      "warning": "#f6ad55",
      "error": "#f56565"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "artistic": {
    "id": "artistic",
    "name": "Artistic",
    "category": "Creative & Artistic",
    "scale": {
      "density": 1.12,
      "radius": 1.33,
      "typeScale": 1.1,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Lora",
      "body": "Inter"
    },
    "colors": {
      "primary": "#9b5b32",
      "secondary": "#7a6d63",
      "neutral": "#201914",
      "base-100": "#fbf6ee",
      "base-200": "#fffdf8",
      "base-300": "#ded2c3",
      "base-content": "#201914",
      "success": "#4f8a4f",
      "warning": "#c9822f",
      "error": "#b33a3a"
    },
    "atmosphere": false,
    "rhythm": 28,
    "mergedFrom": [
      "cafe",
      "elegant",
      "refined",
      "storytelling",
      "warm-editorial"
    ]
  },
  "atelier-zero": {
    "id": "atelier-zero",
    "name": "Atelier Zero",
    "category": "Editorial · Studio",
    "scale": {
      "density": 0.96,
      "radius": 0.67,
      "typeScale": 1.01,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#111111",
      "secondary": "#707070",
      "neutral": "#111111",
      "base-100": "#ffffff",
      "base-200": "#f7f7f7",
      "base-300": "#d9d9d9",
      "base-content": "#111111",
      "success": "#168a46",
      "warning": "#b7791f",
      "error": "#c53030"
    },
    "atmosphere": false,
    "rhythm": 24,
    "mergedFrom": [
      "clean"
    ]
  },
  "bento": {
    "id": "bento",
    "name": "Bento Grid",
    "category": "Layout & Structure",
    "scale": {
      "density": 0.96,
      "radius": 1.33,
      "typeScale": 1.01,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#2563eb",
      "secondary": "#667085",
      "neutral": "#101828",
      "base-100": "#f5f8ff",
      "base-200": "#ffffff",
      "base-300": "#d7e0ef",
      "base-content": "#101828",
      "success": "#16a34a",
      "warning": "#f59e0b",
      "error": "#ef4444"
    },
    "atmosphere": false,
    "rhythm": 24,
    "mergedFrom": [
      "contemporary",
      "corporate",
      "flat",
      "perspective",
      "professional",
      "simple"
    ]
  },
  "binance": {
    "id": "binance",
    "name": "Amber Trade",
    "category": "Fintech & Crypto",
    "scale": {
      "density": 0.8,
      "radius": 1,
      "typeScale": 0.8,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#f0b90b",
      "secondary": "#848e9c",
      "neutral": "#1e2026",
      "base-100": "#ffffff",
      "base-200": "#ffffff",
      "base-300": "#e6e8ea",
      "base-content": "#1e2026",
      "success": "#0ecb81",
      "warning": "#eab308",
      "error": "#f6465d"
    },
    "atmosphere": false,
    "rhythm": 20
  },
  "bmw": {
    "id": "bmw",
    "name": "Autobahn",
    "category": "Automotive",
    "scale": {
      "density": 0.96,
      "radius": 0,
      "typeScale": 0.8,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Space Grotesk",
      "body": "Space Grotesk"
    },
    "colors": {
      "primary": "#1c69d4",
      "secondary": "#757575",
      "neutral": "#262626",
      "base-100": "#ffffff",
      "base-200": "#f5f5f5",
      "base-300": "#e0e0e0",
      "base-content": "#262626",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "bmw-m": {
    "id": "bmw-m",
    "name": "Circuit",
    "category": "Automotive",
    "scale": {
      "density": 1.04,
      "radius": 0.67,
      "typeScale": 1.04,
      "motion": 1,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Space Grotesk",
      "body": "Space Grotesk"
    },
    "colors": {
      "primary": "#0066b1",
      "secondary": "#64748b",
      "neutral": "#111827",
      "base-100": "#f7f8fa",
      "base-200": "#ffffff",
      "base-300": "#d7dee8",
      "base-content": "#111827",
      "success": "#16a34a",
      "warning": "#f59e0b",
      "error": "#e4002b"
    },
    "atmosphere": false,
    "rhythm": 26
  },
  "bold": {
    "id": "bold",
    "name": "Bold",
    "category": "Bold & Expressive",
    "scale": {
      "density": 0.96,
      "radius": 0.67,
      "typeScale": 1.01,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Archivo Black",
      "body": "Inter"
    },
    "colors": {
      "primary": "#111111",
      "secondary": "#707070",
      "neutral": "#111111",
      "base-100": "#ffffff",
      "base-200": "#f7f7f7",
      "base-300": "#d9d9d9",
      "base-content": "#111111",
      "success": "#168a46",
      "warning": "#b7791f",
      "error": "#c53030"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "brutalism": {
    "id": "brutalism",
    "name": "Brutalism",
    "category": "Bold & Expressive",
    "scale": {
      "density": 0.88,
      "radius": 0,
      "typeScale": 1.1,
      "motion": 0.64,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Archivo Black",
      "body": "Inter"
    },
    "colors": {
      "primary": "#ffef5a",
      "secondary": "#555555",
      "neutral": "#000000",
      "base-100": "#f5f1e8",
      "base-200": "#ffffff",
      "base-300": "#000000",
      "base-content": "#000000",
      "success": "#00b050",
      "warning": "#ff8c00",
      "error": "#ff2b2b"
    },
    "atmosphere": false,
    "rhythm": 22
  },
  "bugatti": {
    "id": "bugatti",
    "name": "Hypercar",
    "category": "Automotive",
    "scale": {
      "density": 1.2,
      "radius": 1.17,
      "typeScale": 1.17,
      "motion": 1.27,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Montserrat",
      "body": "Inter"
    },
    "colors": {
      "primary": "#1b4d8f",
      "secondary": "#8fa1b7",
      "neutral": "#f7fbff",
      "base-100": "#07111f",
      "base-200": "#101d2f",
      "base-300": "#2c405c",
      "base-content": "#f7fbff",
      "success": "#2fbf71",
      "warning": "#d9b45f",
      "error": "#c1121f"
    },
    "atmosphere": true,
    "rhythm": 30
  },
  "cal": {
    "id": "cal",
    "name": "Scheduler",
    "category": "Productivity & SaaS",
    "scale": {
      "density": 0.96,
      "radius": 1,
      "typeScale": 0.85,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#0099ff",
      "secondary": "#898989",
      "neutral": "#242424",
      "base-100": "#ffffff",
      "base-200": "#ffffff",
      "base-300": "rgba(34, 42, 53, 0.08)",
      "base-content": "#242424",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "canva": {
    "id": "canva",
    "name": "Palette",
    "category": "Design & Creative",
    "scale": {
      "density": 0.96,
      "radius": 1,
      "typeScale": 0.97,
      "motion": 1.27,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#7d2ae8",
      "secondary": "#5f6368",
      "neutral": "#0e1318",
      "base-100": "#ffffff",
      "base-200": "#f4f5f7",
      "base-300": "#e1e3e6",
      "base-content": "#0e1318",
      "success": "#00b894",
      "warning": "#ffb020",
      "error": "#ff5757"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "cisco": {
    "id": "cisco",
    "name": "Networked",
    "category": "Backend & Data",
    "scale": {
      "density": 1.04,
      "radius": 1.67,
      "typeScale": 0.96,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#049fd9",
      "secondary": "#9e9ea2",
      "neutral": "#ffffff",
      "base-100": "#0f1720",
      "base-200": "#1b2530",
      "base-300": "#58585b",
      "base-content": "#ffffff",
      "success": "#6cc04a",
      "warning": "#ffcc00",
      "error": "#cf2030"
    },
    "atmosphere": true,
    "rhythm": 26
  },
  "claude": {
    "id": "claude",
    "name": "Considered",
    "category": "AI & LLM",
    "scale": {
      "density": 0.96,
      "radius": 1,
      "typeScale": 0.85,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Instrument Serif",
      "body": "Inter"
    },
    "colors": {
      "primary": "#c96442",
      "secondary": "#5e5d59",
      "neutral": "#141413",
      "base-100": "#f5f4ed",
      "base-200": "#faf9f5",
      "base-300": "#f0eee6",
      "base-content": "#141413",
      "success": "#17a34a",
      "warning": "#eab308",
      "error": "#b53333"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "clay": {
    "id": "clay",
    "name": "Clayfield",
    "category": "Design & Creative",
    "scale": {
      "density": 0.96,
      "radius": 1.83,
      "typeScale": 1.01,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#b46a46",
      "secondary": "#8a7a70",
      "neutral": "#2b211c",
      "base-100": "#f7eee6",
      "base-200": "#fff8f1",
      "base-300": "#dac8b9",
      "base-content": "#2b211c",
      "success": "#4d8f5a",
      "warning": "#c88735",
      "error": "#b84c4c"
    },
    "atmosphere": false,
    "rhythm": 24,
    "mergedFrom": [
      "claymorphism",
      "neumorphism"
    ]
  },
  "clickhouse": {
    "id": "clickhouse",
    "name": "Columnar",
    "category": "Backend & Data",
    "scale": {
      "density": 0.64,
      "radius": 0.67,
      "typeScale": 1.28,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#faff69",
      "secondary": "#a0a0a0",
      "neutral": "#ffffff",
      "base-100": "#000000",
      "base-200": "#141414",
      "base-300": "rgba(65, 65, 65, 0.8)",
      "base-content": "#ffffff",
      "success": "#166534",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": true,
    "rhythm": 16
  },
  "cohere": {
    "id": "cohere",
    "name": "Linguist",
    "category": "AI & LLM",
    "scale": {
      "density": 0.6,
      "radius": 1.83,
      "typeScale": 0.96,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#1863dc",
      "secondary": "#93939f",
      "neutral": "#000000",
      "base-100": "#ffffff",
      "base-200": "#fafafa",
      "base-300": "#d9d9dd",
      "base-content": "#000000",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#ef4444"
    },
    "atmosphere": false,
    "rhythm": 15
  },
  "coinbase": {
    "id": "coinbase",
    "name": "Ledger Blue",
    "category": "Fintech & Crypto",
    "scale": {
      "density": 0.96,
      "radius": 1.33,
      "typeScale": 1.06,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#0052ff",
      "secondary": "#5b616e",
      "neutral": "#0a0b0d",
      "base-100": "#ffffff",
      "base-200": "#eef0f3",
      "base-300": "rgba(91, 97, 110, 0.2)",
      "base-content": "#0a0b0d",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "colorful": {
    "id": "colorful",
    "name": "Colorful",
    "category": "Bold & Expressive",
    "scale": {
      "density": 0.96,
      "radius": 1.33,
      "typeScale": 1.01,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#ff6b00",
      "secondary": "#796f91",
      "neutral": "#1d1836",
      "base-100": "#fff8d7",
      "base-200": "#ffffff",
      "base-300": "#eadfba",
      "base-content": "#1d1836",
      "success": "#2e9d57",
      "warning": "#ffb020",
      "error": "#e5484d"
    },
    "atmosphere": false,
    "rhythm": 24,
    "mergedFrom": [
      "creative",
      "energetic",
      "friendly",
      "vibrant"
    ]
  },
  "composio": {
    "id": "composio",
    "name": "Connector",
    "category": "Backend & Data",
    "scale": {
      "density": 0.96,
      "radius": 1.17,
      "typeScale": 0.91,
      "motion": 1,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#6d5dfc",
      "secondary": "#94a3b8",
      "neutral": "#f8fafc",
      "base-100": "#090b14",
      "base-200": "#121626",
      "base-300": "#27324a",
      "base-content": "#f8fafc",
      "success": "#22c55e",
      "warning": "#fbbf24",
      "error": "#fb7185"
    },
    "atmosphere": true,
    "rhythm": 24
  },
  "cosmic": {
    "id": "cosmic",
    "name": "Cosmic",
    "category": "Creative & Artistic",
    "scale": {
      "density": 0.96,
      "radius": 1.33,
      "typeScale": 1.01,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#c084fc",
      "secondary": "#9d8ad4",
      "neutral": "#f8f7ff",
      "base-100": "#070711",
      "base-200": "#111126",
      "base-300": "#34265e",
      "base-content": "#f8f7ff",
      "success": "#39ff88",
      "warning": "#fff34d",
      "error": "#ff4d8d"
    },
    "atmosphere": true,
    "rhythm": 24,
    "mergedFrom": [
      "neon",
      "totality-festival"
    ]
  },
  "cursor": {
    "id": "cursor",
    "name": "Cursorline",
    "category": "Developer Tools",
    "scale": {
      "density": 0.8,
      "radius": 0.83,
      "typeScale": 0.96,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Lora"
    },
    "colors": {
      "primary": "#f54e00",
      "secondary": "rgba(38, 37, 30, 0.55)",
      "neutral": "#26251e",
      "base-100": "#f2f1ed",
      "base-200": "#e6e5e0",
      "base-300": "rgba(38, 37, 30, 0.1)",
      "base-content": "#26251e",
      "success": "#1f8a65",
      "warning": "#eab308",
      "error": "#cf2d56"
    },
    "atmosphere": false,
    "rhythm": 20
  },
  "dashboard": {
    "id": "dashboard",
    "name": "Dashboard",
    "category": "Professional & Corporate",
    "scale": {
      "density": 0.84,
      "radius": 1,
      "typeScale": 0.79,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#0ea5e9",
      "secondary": "#64748b",
      "neutral": "#111827",
      "base-100": "#f4f7fb",
      "base-200": "#ffffff",
      "base-300": "#d8e2ee",
      "base-content": "#111827",
      "success": "#10b981",
      "warning": "#f59e0b",
      "error": "#ef4444"
    },
    "atmosphere": false,
    "rhythm": 21
  },
  "default": {
    "id": "default",
    "name": "Default",
    "category": "Starter",
    "scale": {
      "density": 0.8,
      "radius": 1,
      "typeScale": 0.85,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#2f6feb",
      "secondary": "#6b6b6b",
      "neutral": "#111111",
      "base-100": "#fafafa",
      "base-200": "#ffffff",
      "base-300": "#e5e5e5",
      "base-content": "#111111",
      "success": "#17a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 20
  },
  "discord": {
    "id": "discord",
    "name": "Guildhall",
    "category": "Productivity & SaaS",
    "scale": {
      "density": 0.8,
      "radius": 0.67,
      "typeScale": 0.74,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#5865f2",
      "secondary": "#949ba4",
      "neutral": "#dbdee1",
      "base-100": "#313338",
      "base-200": "#2b2d31",
      "base-300": "rgba(255, 255, 255, 0.06)",
      "base-content": "#dbdee1",
      "success": "#23a55a",
      "warning": "#f0b232",
      "error": "#f23f43"
    },
    "atmosphere": true,
    "rhythm": 20
  },
  "dithered": {
    "id": "dithered",
    "name": "Dithered",
    "category": "Retro & Nostalgic",
    "scale": {
      "density": 0.8,
      "radius": 0.67,
      "typeScale": 0.85,
      "motion": 0.82,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Space Grotesk",
      "body": "Inter"
    },
    "colors": {
      "primary": "#d24b1f",
      "secondary": "#8a6652",
      "neutral": "#2a1810",
      "base-100": "#fff4cf",
      "base-200": "#fffaf0",
      "base-300": "#d9aa7a",
      "base-content": "#2a1810",
      "success": "#3d8f4f",
      "warning": "#f2a93b",
      "error": "#b83a2f"
    },
    "atmosphere": false,
    "rhythm": 20
  },
  "doodle": {
    "id": "doodle",
    "name": "Doodle",
    "category": "Creative & Artistic",
    "scale": {
      "density": 0.96,
      "radius": 1.33,
      "typeScale": 1.01,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Figtree",
      "body": "Figtree"
    },
    "colors": {
      "primary": "#ff6b00",
      "secondary": "#796f91",
      "neutral": "#1d1836",
      "base-100": "#fff8d7",
      "base-200": "#ffffff",
      "base-300": "#eadfba",
      "base-content": "#1d1836",
      "success": "#2e9d57",
      "warning": "#ffb020",
      "error": "#e5484d"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "dramatic": {
    "id": "dramatic",
    "name": "Dramatic",
    "category": "Bold & Expressive",
    "scale": {
      "density": 0.96,
      "radius": 1.33,
      "typeScale": 1.01,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#60a5fa",
      "secondary": "#94a3b8",
      "neutral": "#f8fafc",
      "base-100": "#090b12",
      "base-200": "#121722",
      "base-300": "#2a3447",
      "base-content": "#f8fafc",
      "success": "#22c55e",
      "warning": "#fbbf24",
      "error": "#fb7185"
    },
    "atmosphere": true,
    "rhythm": 24,
    "mergedFrom": [
      "futuristic",
      "sleek"
    ]
  },
  "duolingo": {
    "id": "duolingo",
    "name": "Streak",
    "category": "Productivity & SaaS",
    "scale": {
      "density": 0.8,
      "radius": 1.33,
      "typeScale": 0.79,
      "motion": 1.45,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Anton",
      "body": "Inter"
    },
    "colors": {
      "primary": "#58cc02",
      "secondary": "#777777",
      "neutral": "#3c3c3c",
      "base-100": "#ffffff",
      "base-200": "#f7f7f7",
      "base-300": "#e5e5e5",
      "base-content": "#3c3c3c",
      "success": "#58cc02",
      "warning": "#ffc800",
      "error": "#ff4b4b"
    },
    "atmosphere": false,
    "rhythm": 20
  },
  "editorial": {
    "id": "editorial",
    "name": "Editorial",
    "category": "Creative & Artistic",
    "scale": {
      "density": 1.12,
      "radius": 0.67,
      "typeScale": 1.09,
      "motion": 1.27,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Lora",
      "body": "Lora"
    },
    "colors": {
      "primary": "#9a5a2f",
      "secondary": "#7d7168",
      "neutral": "#1f1a16",
      "base-100": "#fbf7f0",
      "base-200": "#fffdf8",
      "base-300": "#ded3c5",
      "base-content": "#1f1a16",
      "success": "#4f8a4f",
      "warning": "#c9822f",
      "error": "#b33a3a"
    },
    "atmosphere": false,
    "rhythm": 28
  },
  "elevenlabs": {
    "id": "elevenlabs",
    "name": "Waveform",
    "category": "AI & LLM",
    "scale": {
      "density": 0.96,
      "radius": 1.33,
      "typeScale": 0.64,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#000000",
      "secondary": "#777169",
      "neutral": "#000000",
      "base-100": "#ffffff",
      "base-200": "#f5f5f5",
      "base-300": "#e5e5e5",
      "base-content": "#000000",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "enterprise": {
    "id": "enterprise",
    "name": "Enterprise",
    "category": "Professional & Corporate",
    "scale": {
      "density": 0.96,
      "radius": 0.83,
      "typeScale": 0.85,
      "motion": 1.05,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#1d4ed8",
      "secondary": "#64748b",
      "neutral": "#0f172a",
      "base-100": "#f8fafc",
      "base-200": "#ffffff",
      "base-300": "#d8dee8",
      "base-content": "#0f172a",
      "success": "#15803d",
      "warning": "#b45309",
      "error": "#b91c1c"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "expo": {
    "id": "expo",
    "name": "Fieldkit",
    "category": "Developer Tools",
    "scale": {
      "density": 0.96,
      "radius": 1.17,
      "typeScale": 0.9,
      "motion": 1,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#000020",
      "secondary": "#6b7280",
      "neutral": "#0b0d12",
      "base-100": "#ffffff",
      "base-200": "#f6f7f9",
      "base-300": "#dfe3ea",
      "base-content": "#0b0d12",
      "success": "#00a36c",
      "warning": "#f59e0b",
      "error": "#e5484d"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "expressive": {
    "id": "expressive",
    "name": "Expressive",
    "category": "Bold & Expressive",
    "scale": {
      "density": 0.96,
      "radius": 1.33,
      "typeScale": 1.01,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#7c3aed",
      "secondary": "#776b88",
      "neutral": "#1f1730",
      "base-100": "#fbf8ff",
      "base-200": "#ffffff",
      "base-300": "#ded4ee",
      "base-content": "#1f1730",
      "success": "#16a34a",
      "warning": "#f59e0b",
      "error": "#ef4444"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "fantasy": {
    "id": "fantasy",
    "name": "Fantasy",
    "category": "Creative & Artistic",
    "scale": {
      "density": 0.96,
      "radius": 1.33,
      "typeScale": 1.01,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Lora",
      "body": "Inter"
    },
    "colors": {
      "primary": "#c084fc",
      "secondary": "#9d8ad4",
      "neutral": "#f8f7ff",
      "base-100": "#070711",
      "base-200": "#111126",
      "base-300": "#34265e",
      "base-content": "#f8f7ff",
      "success": "#39ff88",
      "warning": "#fff34d",
      "error": "#ff4d8d"
    },
    "atmosphere": true,
    "rhythm": 24
  },
  "ferrari": {
    "id": "ferrari",
    "name": "Rosso",
    "category": "Automotive",
    "scale": {
      "density": 1.12,
      "radius": 0.67,
      "typeScale": 1.17,
      "motion": 1,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Space Grotesk",
      "body": "Space Grotesk"
    },
    "colors": {
      "primary": "#dc0000",
      "secondary": "#a89f91",
      "neutral": "#fffaf0",
      "base-100": "#0b0b0b",
      "base-200": "#171717",
      "base-300": "#342a24",
      "base-content": "#fffaf0",
      "success": "#0f9d58",
      "warning": "#ffd200",
      "error": "#ff3b30"
    },
    "atmosphere": true,
    "rhythm": 28
  },
  "figma": {
    "id": "figma",
    "name": "Canvas Multi",
    "category": "Design & Creative",
    "scale": {
      "density": 0.96,
      "radius": 0.67,
      "typeScale": 1.14,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#000000",
      "secondary": "rgba(0, 0, 0, 0.55)",
      "neutral": "#000000",
      "base-100": "#ffffff",
      "base-200": "#ffffff",
      "base-300": "rgba(0, 0, 0, 0.12)",
      "base-content": "#000000",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "framer": {
    "id": "framer",
    "name": "Motionsmith",
    "category": "Design & Creative",
    "scale": {
      "density": 1.2,
      "radius": 1,
      "typeScale": 1.56,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Poppins",
      "body": "Inter"
    },
    "colors": {
      "primary": "#0099ff",
      "secondary": "rgba(255, 255, 255, 0.6)",
      "neutral": "#ffffff",
      "base-100": "#000000",
      "base-200": "#090909",
      "base-300": "rgba(0, 153, 255, 0.15)",
      "base-content": "#ffffff",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": true,
    "rhythm": 30
  },
  "github": {
    "id": "github",
    "name": "Repository",
    "category": "Developer Tools",
    "scale": {
      "density": 0.64,
      "radius": 0.5,
      "typeScale": 0.6,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#0969da",
      "secondary": "#656d76",
      "neutral": "#1f2328",
      "base-100": "#ffffff",
      "base-200": "#f6f8fa",
      "base-300": "#d0d7de",
      "base-content": "#1f2328",
      "success": "#1a7f37",
      "warning": "#9a6700",
      "error": "#cf222e"
    },
    "atmosphere": false,
    "rhythm": 16
  },
  "glassmorphism": {
    "id": "glassmorphism",
    "name": "Glassmorphism",
    "category": "Morphism & Effects",
    "scale": {
      "density": 1.04,
      "radius": 2,
      "typeScale": 1.01,
      "motion": 1.27,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#4f8cff",
      "secondary": "#60708a",
      "neutral": "#102033",
      "base-100": "#eef6ff",
      "base-200": "rgba(255, 255, 255, 0.74)",
      "base-300": "rgba(255, 255, 255, 0.64)",
      "base-content": "#102033",
      "success": "#22c55e",
      "warning": "#f59e0b",
      "error": "#ef4444"
    },
    "atmosphere": false,
    "rhythm": 26
  },
  "gradient": {
    "id": "gradient",
    "name": "Gradient",
    "category": "Morphism & Effects",
    "scale": {
      "density": 1.04,
      "radius": 1.67,
      "typeScale": 1.14,
      "motion": 1.18,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#7c3aed",
      "secondary": "#746985",
      "neutral": "#191225",
      "base-100": "#f7f3ff",
      "base-200": "#ffffff",
      "base-300": "#ddd2f2",
      "base-content": "#191225",
      "success": "#10b981",
      "warning": "#f59e0b",
      "error": "#ef4444"
    },
    "atmosphere": false,
    "rhythm": 26
  },
  "hashicorp": {
    "id": "hashicorp",
    "name": "Terraform Dark",
    "category": "Backend & Data",
    "scale": {
      "density": 0.8,
      "radius": 0.67,
      "typeScale": 1.09,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#1060ff",
      "secondary": "#b2b6bd",
      "neutral": "#efeff1",
      "base-100": "#15181e",
      "base-200": "#0d0e12",
      "base-300": "rgba(178, 182, 189, 0.4)",
      "base-content": "#efeff1",
      "success": "#16a34a",
      "warning": "#bb5a00",
      "error": "#dc2626"
    },
    "atmosphere": true,
    "rhythm": 20
  },
  "hud": {
    "id": "hud",
    "name": "Hud",
    "category": "Themed & Unique",
    "scale": {
      "density": 0.8,
      "radius": 1.33,
      "typeScale": 0.85,
      "motion": 0.82,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Space Grotesk",
      "body": "Space Grotesk"
    },
    "colors": {
      "primary": "#60a5fa",
      "secondary": "#94a3b8",
      "neutral": "#f8fafc",
      "base-100": "#090b12",
      "base-200": "#121722",
      "base-300": "#2a3447",
      "base-content": "#f8fafc",
      "success": "#22c55e",
      "warning": "#fbbf24",
      "error": "#fb7185"
    },
    "atmosphere": true,
    "rhythm": 20
  },
  "huggingface": {
    "id": "huggingface",
    "name": "Open Weights",
    "category": "AI & LLM",
    "scale": {
      "density": 0.8,
      "radius": 0.5,
      "typeScale": 0.68,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Space Grotesk",
      "body": "Inter"
    },
    "colors": {
      "primary": "#ffd21e",
      "secondary": "#6b7280",
      "neutral": "#0d1117",
      "base-100": "#fafafa",
      "base-200": "#ffffff",
      "base-300": "#e5e7eb",
      "base-content": "#0d1117",
      "success": "#16a34a",
      "warning": "#f59e0b",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 20
  },
  "ibm": {
    "id": "ibm",
    "name": "Mainframe",
    "category": "Media & Consumer",
    "scale": {
      "density": 0.96,
      "radius": 0,
      "typeScale": 0.8,
      "motion": 0.82,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#0f62fe",
      "secondary": "#6f6f6f",
      "neutral": "#161616",
      "base-100": "#ffffff",
      "base-200": "#f4f4f4",
      "base-300": "#c6c6c6",
      "base-content": "#161616",
      "success": "#24a148",
      "warning": "#f1c21b",
      "error": "#da1e28"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "intercom": {
    "id": "intercom",
    "name": "Conversational",
    "category": "Productivity & SaaS",
    "scale": {
      "density": 0.96,
      "radius": 0.5,
      "typeScale": 1.06,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#ff5600",
      "secondary": "#7b7b78",
      "neutral": "#111111",
      "base-100": "#faf9f6",
      "base-200": "#ffffff",
      "base-300": "#dedbd6",
      "base-content": "#111111",
      "success": "#00da00",
      "warning": "#eab308",
      "error": "#c41c1c"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "kami": {
    "id": "kami",
    "name": "Papercut",
    "category": "Editorial & Print",
    "scale": {
      "density": 0.72,
      "radius": 0.67,
      "typeScale": 1.46,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Lora",
      "body": "Lora"
    },
    "colors": {
      "primary": "#1b365d",
      "secondary": "#504e49",
      "neutral": "#141413",
      "base-100": "#f5f4ed",
      "base-200": "#faf9f5",
      "base-300": "#e8e6dc",
      "base-content": "#141413",
      "success": "#4a6b3a",
      "warning": "#8a6b1f",
      "error": "#8a3a30"
    },
    "atmosphere": false,
    "rhythm": 18
  },
  "kraken": {
    "id": "kraken",
    "name": "Deepwater",
    "category": "Fintech & Crypto",
    "scale": {
      "density": 0.88,
      "radius": 1,
      "typeScale": 0.85,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#7132f5",
      "secondary": "#8b95aa",
      "neutral": "#f8fafc",
      "base-100": "#0b1020",
      "base-200": "#121a33",
      "base-300": "#26314f",
      "base-content": "#f8fafc",
      "success": "#00c853",
      "warning": "#ffb020",
      "error": "#ff4d6d"
    },
    "atmosphere": true,
    "rhythm": 22
  },
  "lamborghini": {
    "id": "lamborghini",
    "name": "Angular",
    "category": "Automotive",
    "scale": {
      "density": 1.12,
      "radius": 0.5,
      "typeScale": 1.2,
      "motion": 0.95,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Montserrat",
      "body": "Inter"
    },
    "colors": {
      "primary": "#d4af37",
      "secondary": "#9b927d",
      "neutral": "#f8f4e6",
      "base-100": "#050505",
      "base-200": "#141414",
      "base-300": "#3a321d",
      "base-content": "#f8f4e6",
      "success": "#39a852",
      "warning": "#f7c948",
      "error": "#e63946"
    },
    "atmosphere": true,
    "rhythm": 28
  },
  "levels": {
    "id": "levels",
    "name": "Metric",
    "category": "Layout & Structure",
    "scale": {
      "density": 0.96,
      "radius": 1.5,
      "typeScale": 0.88,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#2f8f46",
      "secondary": "#788276",
      "neutral": "#1f2a24",
      "base-100": "#fbf7ef",
      "base-200": "#ffffff",
      "base-300": "#dbe3d7",
      "base-content": "#1f2a24",
      "success": "#16a34a",
      "warning": "#d97706",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "linear-app": {
    "id": "linear-app",
    "name": "Tracked",
    "category": "Productivity & SaaS",
    "scale": {
      "density": 0.8,
      "radius": 0.67,
      "typeScale": 0.96,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#5e6ad2",
      "secondary": "#8a8f98",
      "neutral": "#f7f8f8",
      "base-100": "#08090a",
      "base-200": "#191a1b",
      "base-300": "rgba(255, 255, 255, 0.08)",
      "base-content": "#f7f8f8",
      "success": "#27a644",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": true,
    "rhythm": 20
  },
  "lingo": {
    "id": "lingo",
    "name": "Phrasebook",
    "category": "Creative & Artistic",
    "scale": {
      "density": 0.96,
      "radius": 1.33,
      "typeScale": 0.93,
      "motion": 1.05,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#6d4aff",
      "secondary": "#786f8f",
      "neutral": "#1d1b2a",
      "base-100": "#fbf9ff",
      "base-200": "#ffffff",
      "base-300": "#ded7f0",
      "base-content": "#1d1b2a",
      "success": "#22a06b",
      "warning": "#e6a700",
      "error": "#e5484d"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "loom": {
    "id": "loom",
    "name": "Recorded",
    "category": "Themed & Unique",
    "scale": {
      "density": 0.72,
      "radius": 0.5,
      "typeScale": 0.61,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#625df5",
      "secondary": "#6b6d76",
      "neutral": "#1f1f23",
      "base-100": "#ffffff",
      "base-200": "#f7f7f8",
      "base-300": "#e4e4e7",
      "base-content": "#1f1f23",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#d64770"
    },
    "atmosphere": false,
    "rhythm": 18
  },
  "lovable": {
    "id": "lovable",
    "name": "Vibe Build",
    "category": "Developer Tools",
    "scale": {
      "density": 1.28,
      "radius": 1,
      "typeScale": 0.8,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#ff4d8d",
      "secondary": "#5f5f5d",
      "neutral": "#1c1c1c",
      "base-100": "#f7f4ed",
      "base-200": "#f7f4ed",
      "base-300": "#eceae4",
      "base-content": "#1c1c1c",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 32
  },
  "luxury": {
    "id": "luxury",
    "name": "Luxury",
    "category": "Professional & Corporate",
    "scale": {
      "density": 1.2,
      "radius": 1.17,
      "typeScale": 1.28,
      "motion": 1.36,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Playfair Display",
      "body": "Inter"
    },
    "colors": {
      "primary": "#c6a15b",
      "secondary": "#9f927c",
      "neutral": "#fff8ea",
      "base-100": "#080706",
      "base-200": "#151310",
      "base-300": "#3a3020",
      "base-content": "#fff8ea",
      "success": "#5fa36a",
      "warning": "#d8a94f",
      "error": "#d85a52"
    },
    "atmosphere": true,
    "rhythm": 30
  },
  "mastercard": {
    "id": "mastercard",
    "name": "Interlock",
    "category": "Fintech & Crypto",
    "scale": {
      "density": 1.04,
      "radius": 3,
      "typeScale": 0.85,
      "motion": 1.18,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#cf4500",
      "secondary": "#696969",
      "neutral": "#141413",
      "base-100": "#f3f0ee",
      "base-200": "#fcfbfa",
      "base-300": "#d1cdc7",
      "base-content": "#141413",
      "success": "#2e7d32",
      "warning": "#f79e1b",
      "error": "#eb001b"
    },
    "atmosphere": false,
    "rhythm": 26
  },
  "material": {
    "id": "material",
    "name": "Material",
    "category": "Professional & Corporate",
    "scale": {
      "density": 0.96,
      "radius": 1,
      "typeScale": 0.85,
      "motion": 1.14,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#1a73e8",
      "secondary": "#5f6368",
      "neutral": "#202124",
      "base-100": "#f8fafd",
      "base-200": "#ffffff",
      "base-300": "#dadce0",
      "base-content": "#202124",
      "success": "#188038",
      "warning": "#f9ab00",
      "error": "#d93025"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "meta": {
    "id": "meta",
    "name": "Social Blue",
    "category": "E-Commerce & Retail",
    "scale": {
      "density": 0.8,
      "radius": 1.67,
      "typeScale": 0.85,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#0064e0",
      "secondary": "#65676b",
      "neutral": "#1c2b33",
      "base-100": "#ffffff",
      "base-200": "#f7f8fa",
      "base-300": "#ced0d4",
      "base-content": "#1c2b33",
      "success": "#31a24c",
      "warning": "#f7b928",
      "error": "#e41e3f"
    },
    "atmosphere": false,
    "rhythm": 20
  },
  "minimal": {
    "id": "minimal",
    "name": "Minimal",
    "category": "Modern & Minimal",
    "scale": {
      "density": 1.12,
      "radius": 0.33,
      "typeScale": 0.85,
      "motion": 1,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#111111",
      "secondary": "#777777",
      "neutral": "#111111",
      "base-100": "#ffffff",
      "base-200": "#fafafa",
      "base-300": "#e2e2e2",
      "base-content": "#111111",
      "success": "#168a46",
      "warning": "#b7791f",
      "error": "#c53030"
    },
    "atmosphere": false,
    "rhythm": 28
  },
  "minimax": {
    "id": "minimax",
    "name": "Sparse",
    "category": "AI & LLM",
    "scale": {
      "density": 0.8,
      "radius": 1.08,
      "typeScale": 1.06,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Figtree",
      "body": "Inter"
    },
    "colors": {
      "primary": "#1456f0",
      "secondary": "#45515e",
      "neutral": "#222222",
      "base-100": "#ffffff",
      "base-200": "#fafafa",
      "base-300": "#e5e7eb",
      "base-content": "#222222",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 20
  },
  "mintlify": {
    "id": "mintlify",
    "name": "Documented",
    "category": "Productivity & SaaS",
    "scale": {
      "density": 0.96,
      "radius": 1.33,
      "typeScale": 0.85,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#18E299",
      "secondary": "#666666",
      "neutral": "#0d0d0d",
      "base-100": "#ffffff",
      "base-200": "#ffffff",
      "base-300": "rgba(0, 0, 0, 0.05)",
      "base-content": "#0d0d0d",
      "success": "#16a34a",
      "warning": "#c37d0d",
      "error": "#d45656"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "miro": {
    "id": "miro",
    "name": "Whiteboard",
    "category": "Design & Creative",
    "scale": {
      "density": 1.04,
      "radius": 1.5,
      "typeScale": 1.01,
      "motion": 1.05,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#ffd02f",
      "secondary": "#605a8a",
      "neutral": "#050038",
      "base-100": "#fff7c2",
      "base-200": "#ffffff",
      "base-300": "#ded9ff",
      "base-content": "#050038",
      "success": "#1a7f37",
      "warning": "#ff9f1c",
      "error": "#d92d20"
    },
    "atmosphere": false,
    "rhythm": 26
  },
  "mission-control": {
    "id": "mission-control",
    "name": "Mission Control",
    "category": "Developer Tools",
    "scale": {
      "density": 0.8,
      "radius": 1.33,
      "typeScale": 0.85,
      "motion": 0.82,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#60a5fa",
      "secondary": "#94a3b8",
      "neutral": "#f8fafc",
      "base-100": "#090b12",
      "base-200": "#121722",
      "base-300": "#2a3447",
      "base-content": "#f8fafc",
      "success": "#26de81",
      "warning": "#fbbf24",
      "error": "#ff4757"
    },
    "atmosphere": true,
    "rhythm": 20
  },
  "mistral-ai": {
    "id": "mistral-ai",
    "name": "Mistral Wind",
    "category": "AI & LLM",
    "scale": {
      "density": 0.8,
      "radius": 0.17,
      "typeScale": 1.09,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#fa520f",
      "secondary": "#3d3d3d",
      "neutral": "#1f1f1f",
      "base-100": "#fffaeb",
      "base-200": "#fff0c2",
      "base-300": "#f0e8c8",
      "base-content": "#1f1f1f",
      "success": "#17a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 20
  },
  "modern": {
    "id": "modern",
    "name": "Modern",
    "category": "Modern & Minimal",
    "scale": {
      "density": 1.04,
      "radius": 1.33,
      "typeScale": 1.01,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#4f46e5",
      "secondary": "#6b7280",
      "neutral": "#111827",
      "base-100": "#f7f8fc",
      "base-200": "#ffffff",
      "base-300": "#dfe3ed",
      "base-content": "#111827",
      "success": "#10b981",
      "warning": "#f59e0b",
      "error": "#ef4444"
    },
    "atmosphere": false,
    "rhythm": 26
  },
  "mongodb": {
    "id": "mongodb",
    "name": "Document Store",
    "category": "Backend & Data",
    "scale": {
      "density": 0.96,
      "radius": 0.67,
      "typeScale": 1.28,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Lora",
      "body": "Poppins"
    },
    "colors": {
      "primary": "#00ed64",
      "secondary": "#b8c4c2",
      "neutral": "#ffffff",
      "base-100": "#001e2b",
      "base-200": "#1c2d38",
      "base-300": "#3d4f58",
      "base-content": "#ffffff",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": true,
    "rhythm": 24
  },
  "mono": {
    "id": "mono",
    "name": "Mono",
    "category": "Modern & Minimal",
    "scale": {
      "density": 0.8,
      "radius": 0.67,
      "typeScale": 0.85,
      "motion": 0.82,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Space Grotesk",
      "body": "Space Grotesk"
    },
    "colors": {
      "primary": "#111111",
      "secondary": "#707070",
      "neutral": "#111111",
      "base-100": "#ffffff",
      "base-200": "#f7f7f7",
      "base-300": "#d9d9d9",
      "base-content": "#111111",
      "success": "#168a46",
      "warning": "#b7791f",
      "error": "#c53030"
    },
    "atmosphere": false,
    "rhythm": 20
  },
  "neobrutalism": {
    "id": "neobrutalism",
    "name": "Neobrutalism",
    "category": "Bold & Expressive",
    "scale": {
      "density": 0.96,
      "radius": 0.67,
      "typeScale": 1.01,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Archivo Black",
      "body": "Inter"
    },
    "colors": {
      "primary": "#d24b1f",
      "secondary": "#8a6652",
      "neutral": "#2a1810",
      "base-100": "#fff4cf",
      "base-200": "#fffaf0",
      "base-300": "#d9aa7a",
      "base-content": "#2a1810",
      "success": "#3d8f4f",
      "warning": "#f2a93b",
      "error": "#b83a2f"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "nike": {
    "id": "nike",
    "name": "Momentum",
    "category": "E-Commerce & Retail",
    "scale": {
      "density": 0.8,
      "radius": 1.67,
      "typeScale": 1.28,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Montserrat",
      "body": "Inter"
    },
    "colors": {
      "primary": "#111111",
      "secondary": "#707072",
      "neutral": "#111111",
      "base-100": "#ffffff",
      "base-200": "#f5f5f5",
      "base-300": "#cacacb",
      "base-content": "#111111",
      "success": "#007d48",
      "warning": "#fca600",
      "error": "#d30005"
    },
    "atmosphere": false,
    "rhythm": 20
  },
  "notion": {
    "id": "notion",
    "name": "Notebook",
    "category": "Productivity & SaaS",
    "scale": {
      "density": 0.8,
      "radius": 0.67,
      "typeScale": 0.85,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#0075de",
      "secondary": "#615d59",
      "neutral": "rgba(0, 0, 0, 0.95)",
      "base-100": "#ffffff",
      "base-200": "#f6f5f4",
      "base-300": "rgba(0, 0, 0, 0.1)",
      "base-content": "rgba(0, 0, 0, 0.95)",
      "success": "#1aae39",
      "warning": "#dd5b00",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 20
  },
  "nvidia": {
    "id": "nvidia",
    "name": "Compute Green",
    "category": "Media & Consumer",
    "scale": {
      "density": 0.64,
      "radius": 0.17,
      "typeScale": 0.6,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#76b900",
      "secondary": "#757575",
      "neutral": "#ffffff",
      "base-100": "#000000",
      "base-200": "#1a1a1a",
      "base-300": "#5e5e5e",
      "base-content": "#ffffff",
      "success": "#3f8500",
      "warning": "#ef9100",
      "error": "#e52020"
    },
    "atmosphere": true,
    "rhythm": 16
  },
  "ollama": {
    "id": "ollama",
    "name": "Local Model",
    "category": "AI & LLM",
    "scale": {
      "density": 1.12,
      "radius": 1,
      "typeScale": 0.64,
      "motion": 0.64,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Manrope",
      "body": "Inter"
    },
    "colors": {
      "primary": "#000000",
      "secondary": "#737373",
      "neutral": "#000000",
      "base-100": "#ffffff",
      "base-200": "#fafafa",
      "base-300": "#e5e5e5",
      "base-content": "#000000",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 28
  },
  "openai": {
    "id": "openai",
    "name": "Assistant",
    "category": "AI & LLM",
    "scale": {
      "density": 0.96,
      "radius": 1.33,
      "typeScale": 0.74,
      "motion": 1,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Playfair Display",
      "body": "Inter"
    },
    "colors": {
      "primary": "#10a37f",
      "secondary": "#6e6e6e",
      "neutral": "#0d0d0d",
      "base-100": "#ffffff",
      "base-200": "#f5f5f5",
      "base-300": "#e5e5e5",
      "base-content": "#0d0d0d",
      "success": "#10a37f",
      "warning": "#f5a623",
      "error": "#ef4146"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "opencode-ai": {
    "id": "opencode-ai",
    "name": "Open Terminal",
    "category": "AI & LLM",
    "scale": {
      "density": 0.8,
      "radius": 0.5,
      "typeScale": 0.64,
      "motion": 0.68,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Space Grotesk",
      "body": "Space Grotesk"
    },
    "colors": {
      "primary": "#007aff",
      "secondary": "#9a9898",
      "neutral": "#fdfcfc",
      "base-100": "#201d1d",
      "base-200": "#302c2c",
      "base-300": "#464343",
      "base-content": "#fdfcfc",
      "success": "#30d158",
      "warning": "#ff9f0a",
      "error": "#ff3b30"
    },
    "atmosphere": true,
    "rhythm": 20
  },
  "pacman": {
    "id": "pacman",
    "name": "Arcade",
    "category": "Themed & Unique",
    "scale": {
      "density": 0.84,
      "radius": 1.5,
      "typeScale": 0.97,
      "motion": 0.73,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Archivo Black",
      "body": "Inter"
    },
    "colors": {
      "primary": "#ffcc00",
      "secondary": "#b9a85d",
      "neutral": "#fff7d6",
      "base-100": "#050505",
      "base-200": "#101014",
      "base-300": "#2338ff",
      "base-content": "#fff7d6",
      "success": "#00ff66",
      "warning": "#ff9900",
      "error": "#ff3b3b"
    },
    "atmosphere": true,
    "rhythm": 21
  },
  "paper": {
    "id": "paper",
    "name": "Paper",
    "category": "Retro & Nostalgic",
    "scale": {
      "density": 1.12,
      "radius": 1.33,
      "typeScale": 1.1,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Lora",
      "body": "Inter"
    },
    "colors": {
      "primary": "#8f5d24",
      "secondary": "#7c7160",
      "neutral": "#211b12",
      "base-100": "#faf3df",
      "base-200": "#fffaf0",
      "base-300": "#ddd0b4",
      "base-content": "#211b12",
      "success": "#5b8d42",
      "warning": "#c27b22",
      "error": "#a64036"
    },
    "atmosphere": false,
    "rhythm": 28,
    "mergedFrom": [
      "vintage"
    ]
  },
  "perplexity": {
    "id": "perplexity",
    "name": "Answer Engine",
    "category": "AI & LLM",
    "scale": {
      "density": 0.64,
      "radius": 0.67,
      "typeScale": 0.6,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#a855f7",
      "secondary": "#9b9b9b",
      "neutral": "#f0f0f0",
      "base-100": "#0f0f10",
      "base-200": "#19191a",
      "base-300": "#2e2e30",
      "base-content": "#f0f0f0",
      "success": "#22c55e",
      "warning": "#f59e0b",
      "error": "#ef4444"
    },
    "atmosphere": true,
    "rhythm": 16
  },
  "pinterest": {
    "id": "pinterest",
    "name": "Moodboard",
    "category": "Media & Consumer",
    "scale": {
      "density": 0.8,
      "radius": 1.33,
      "typeScale": 0.93,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#e60023",
      "secondary": "#62625b",
      "neutral": "#211922",
      "base-100": "#ffffff",
      "base-200": "#f6f6f3",
      "base-300": "#c8c8c1",
      "base-content": "#211922",
      "success": "#103c25",
      "warning": "#c47700",
      "error": "#9e0a0a"
    },
    "atmosphere": false,
    "rhythm": 20
  },
  "playstation": {
    "id": "playstation",
    "name": "Console",
    "category": "Media & Consumer",
    "scale": {
      "density": 0.96,
      "radius": 1,
      "typeScale": 0.64,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#0070cc",
      "secondary": "#cccccc",
      "neutral": "#ffffff",
      "base-100": "#000000",
      "base-200": "#ffffff",
      "base-300": "#cccccc",
      "base-content": "#ffffff",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#c81b3a"
    },
    "atmosphere": true,
    "rhythm": 24
  },
  "posthog": {
    "id": "posthog",
    "name": "Funnel",
    "category": "Backend & Data",
    "scale": {
      "density": 0.48,
      "radius": 0.5,
      "typeScale": 0.6,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#F54E00",
      "secondary": "#65675e",
      "neutral": "#4d4f46",
      "base-100": "#fdfdf8",
      "base-200": "#eeefe9",
      "base-300": "#bfc1b7",
      "base-content": "#4d4f46",
      "success": "#16a34a",
      "warning": "#F7A501",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 12
  },
  "premium": {
    "id": "premium",
    "name": "Premium",
    "category": "Professional & Corporate",
    "scale": {
      "density": 1.12,
      "radius": 1.33,
      "typeScale": 1.12,
      "motion": 1.27,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Playfair Display",
      "body": "Inter"
    },
    "colors": {
      "primary": "#a06a3b",
      "secondary": "#746d63",
      "neutral": "#1c1b19",
      "base-100": "#faf8f4",
      "base-200": "#ffffff",
      "base-300": "#ded6c9",
      "base-content": "#1c1b19",
      "success": "#3f8f5f",
      "warning": "#c4872c",
      "error": "#b84a4a"
    },
    "atmosphere": false,
    "rhythm": 28
  },
  "publication": {
    "id": "publication",
    "name": "Publication",
    "category": "Creative & Artistic",
    "scale": {
      "density": 0.88,
      "radius": 0,
      "typeScale": 1.1,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Lora"
    },
    "colors": {
      "primary": "#c1121f",
      "secondary": "#666666",
      "neutral": "#0b0b0b",
      "base-100": "#ffffff",
      "base-200": "#f6f6f6",
      "base-300": "#d6d6d6",
      "base-content": "#0b0b0b",
      "success": "#0f8a3b",
      "warning": "#d99a00",
      "error": "#b00020"
    },
    "atmosphere": false,
    "rhythm": 22
  },
  "raycast": {
    "id": "raycast",
    "name": "Command Bar",
    "category": "Developer Tools",
    "scale": {
      "density": 0.96,
      "radius": 1,
      "typeScale": 0.85,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#FF6363",
      "secondary": "#9c9c9d",
      "neutral": "#f9f9f9",
      "base-100": "#07080a",
      "base-200": "#101111",
      "base-300": "rgba(255, 255, 255, 0.06)",
      "base-content": "#f9f9f9",
      "success": "hsl(151, 59%, 59%)",
      "warning": "hsl(43, 100%, 60%)",
      "error": "hsl(0, 100%, 69%)"
    },
    "atmosphere": true,
    "rhythm": 24
  },
  "renault": {
    "id": "renault",
    "name": "Continental",
    "category": "Automotive",
    "scale": {
      "density": 1.04,
      "radius": 0.67,
      "typeScale": 1.09,
      "motion": 1.05,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#ffcc33",
      "secondary": "#6f6b63",
      "neutral": "#111111",
      "base-100": "#f7f4ef",
      "base-200": "#ffffff",
      "base-300": "#dfd8ca",
      "base-content": "#111111",
      "success": "#198754",
      "warning": "#f59e0b",
      "error": "#d92d20"
    },
    "atmosphere": false,
    "rhythm": 26
  },
  "replicate": {
    "id": "replicate",
    "name": "Inference",
    "category": "AI & LLM",
    "scale": {
      "density": 0.96,
      "radius": 3,
      "typeScale": 1.7,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#ea2804",
      "secondary": "#646464",
      "neutral": "#202020",
      "base-100": "#ffffff",
      "base-200": "#f8f8f8",
      "base-300": "#202020",
      "base-content": "#202020",
      "success": "#2b9a66",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "resend": {
    "id": "resend",
    "name": "Deliverable",
    "category": "Productivity & SaaS",
    "scale": {
      "density": 1.2,
      "radius": 0.67,
      "typeScale": 1.28,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#ff801f",
      "secondary": "#5c5c5c",
      "neutral": "#f0f0f0",
      "base-100": "#000000",
      "base-200": "#000000",
      "base-300": "rgba(214, 235, 253, 0.19)",
      "base-content": "#f0f0f0",
      "success": "#11ff99",
      "warning": "#ffc53d",
      "error": "#ff2047"
    },
    "atmosphere": true,
    "rhythm": 30
  },
  "retro": {
    "id": "retro",
    "name": "Retro",
    "category": "Retro & Nostalgic",
    "scale": {
      "density": 0.96,
      "radius": 0.67,
      "typeScale": 1.01,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Space Grotesk",
      "body": "Inter"
    },
    "colors": {
      "primary": "#d24b1f",
      "secondary": "#8a6652",
      "neutral": "#2a1810",
      "base-100": "#fff4cf",
      "base-200": "#fffaf0",
      "base-300": "#d9aa7a",
      "base-content": "#2a1810",
      "success": "#3d8f4f",
      "warning": "#f2a93b",
      "error": "#b83a2f"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "revolut": {
    "id": "revolut",
    "name": "Neobank",
    "category": "Fintech & Crypto",
    "scale": {
      "density": 1.04,
      "radius": 1.67,
      "typeScale": 1.01,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#0666eb",
      "secondary": "#64748b",
      "neutral": "#111827",
      "base-100": "#f7f8fb",
      "base-200": "#ffffff",
      "base-300": "#dbe3ef",
      "base-content": "#111827",
      "success": "#16a34a",
      "warning": "#f59e0b",
      "error": "#ef4444"
    },
    "atmosphere": false,
    "rhythm": 26
  },
  "runwayml": {
    "id": "runwayml",
    "name": "Generative Frame",
    "category": "AI & LLM",
    "scale": {
      "density": 0.78,
      "radius": 0.67,
      "typeScale": 0.64,
      "motion": 1,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#ffffff",
      "secondary": "#767d88",
      "neutral": "#ffffff",
      "base-100": "#000000",
      "base-200": "#1a1a1a",
      "base-300": "#27272a",
      "base-content": "#ffffff",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": true,
    "rhythm": 20
  },
  "sanity": {
    "id": "sanity",
    "name": "Structured Content",
    "category": "Backend & Data",
    "scale": {
      "density": 0.96,
      "radius": 0.83,
      "typeScale": 0.85,
      "motion": 0.95,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#f03e2f",
      "secondary": "#71717a",
      "neutral": "#171717",
      "base-100": "#f8f8f7",
      "base-200": "#ffffff",
      "base-300": "#e4e4e7",
      "base-content": "#171717",
      "success": "#16a34a",
      "warning": "#f59e0b",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "sentry": {
    "id": "sentry",
    "name": "Stacktrace",
    "category": "Backend & Data",
    "scale": {
      "density": 0.8,
      "radius": 0.67,
      "typeScale": 1.17,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Figtree"
    },
    "colors": {
      "primary": "#6a5fc1",
      "secondary": "#9d96b3",
      "neutral": "#ffffff",
      "base-100": "#1f1633",
      "base-200": "#150f23",
      "base-300": "#362d59",
      "base-content": "#ffffff",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": true,
    "rhythm": 20
  },
  "shadcn": {
    "id": "shadcn",
    "name": "Unstyled",
    "category": "Modern & Minimal",
    "scale": {
      "density": 0.96,
      "radius": 0.67,
      "typeScale": 0.64,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#000000",
      "secondary": "#64748b",
      "neutral": "#111827",
      "base-100": "#ffffff",
      "base-200": "#ffffff",
      "base-300": "#e5e7eb",
      "base-content": "#111827",
      "success": "#16a34a",
      "warning": "#d97706",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "shopify": {
    "id": "shopify",
    "name": "Storefront Green",
    "category": "E-Commerce & Retail",
    "scale": {
      "density": 0.96,
      "radius": 0.67,
      "typeScale": 1.13,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#36f4a4",
      "secondary": "#a1a1aa",
      "neutral": "#ffffff",
      "base-100": "#000000",
      "base-200": "#02090a",
      "base-300": "#1e2c31",
      "base-content": "#ffffff",
      "success": "#36f4a4",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": true,
    "rhythm": 24
  },
  "skeumorphism": {
    "id": "skeumorphism",
    "name": "Skeumorphism",
    "category": "Morphism & Effects",
    "scale": {
      "density": 0.96,
      "radius": 1.83,
      "typeScale": 1.01,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Lora",
      "body": "Inter"
    },
    "colors": {
      "primary": "#b46a46",
      "secondary": "#8a7a70",
      "neutral": "#2b211c",
      "base-100": "#f7eee6",
      "base-200": "#fff8f1",
      "base-300": "#dac8b9",
      "base-content": "#2b211c",
      "success": "#4d8f5a",
      "warning": "#c88735",
      "error": "#b84c4c"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "slack": {
    "id": "slack",
    "name": "Channel",
    "category": "Productivity & SaaS",
    "scale": {
      "density": 0.8,
      "radius": 0.67,
      "typeScale": 0.68,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#4a154b",
      "secondary": "#616061",
      "neutral": "#1d1c1d",
      "base-100": "#ffffff",
      "base-200": "#f8f8f8",
      "base-300": "#dddddd",
      "base-content": "#1d1c1d",
      "success": "#2eb67d",
      "warning": "#ecb22e",
      "error": "#e01e5a"
    },
    "atmosphere": false,
    "rhythm": 20
  },
  "spacex": {
    "id": "spacex",
    "name": "Launch",
    "category": "Media & Consumer",
    "scale": {
      "density": 1.2,
      "radius": 0.33,
      "typeScale": 0.64,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Space Grotesk",
      "body": "Space Grotesk"
    },
    "colors": {
      "primary": "#f0f0fa",
      "secondary": "rgba(240, 240, 250, 0.7)",
      "neutral": "#f0f0fa",
      "base-100": "#000000",
      "base-200": "#000000",
      "base-300": "rgba(240, 240, 250, 0.35)",
      "base-content": "#f0f0fa",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": true,
    "rhythm": 30
  },
  "spacious": {
    "id": "spacious",
    "name": "Spacious",
    "category": "Layout & Structure",
    "scale": {
      "density": 1.12,
      "radius": 1.33,
      "typeScale": 1.1,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#8f5d24",
      "secondary": "#7c7160",
      "neutral": "#211b12",
      "base-100": "#faf3df",
      "base-200": "#fffaf0",
      "base-300": "#ddd0b4",
      "base-content": "#211b12",
      "success": "#5b8d42",
      "warning": "#c27b22",
      "error": "#a64036"
    },
    "atmosphere": false,
    "rhythm": 28
  },
  "spotify": {
    "id": "spotify",
    "name": "Playlist",
    "category": "Media & Consumer",
    "scale": {
      "density": 0.64,
      "radius": 0.5,
      "typeScale": 0.6,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#1ed760",
      "secondary": "#b3b3b3",
      "neutral": "#ffffff",
      "base-100": "#121212",
      "base-200": "#181818",
      "base-300": "#4d4d4d",
      "base-content": "#ffffff",
      "success": "#1ed760",
      "warning": "#ffa42b",
      "error": "#f3727f"
    },
    "atmosphere": true,
    "rhythm": 16
  },
  "starbucks": {
    "id": "starbucks",
    "name": "Roastery",
    "category": "E-Commerce & Retail",
    "scale": {
      "density": 0.64,
      "radius": 1,
      "typeScale": 0.77,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#00754A",
      "secondary": "rgba(0, 0, 0, 0.58)",
      "neutral": "rgba(0, 0, 0, 0.87)",
      "base-100": "#f2f0eb",
      "base-200": "#ffffff",
      "base-300": "#d6dbde",
      "base-content": "rgba(0, 0, 0, 0.87)",
      "success": "#16a34a",
      "warning": "#fbbc05",
      "error": "#c82014"
    },
    "atmosphere": false,
    "rhythm": 16
  },
  "stripe": {
    "id": "stripe",
    "name": "Checkout Indigo",
    "category": "Fintech & Crypto",
    "scale": {
      "density": 0.96,
      "radius": 0.5,
      "typeScale": 0.74,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#533afd",
      "secondary": "#64748d",
      "neutral": "#061b31",
      "base-100": "#ffffff",
      "base-200": "#ffffff",
      "base-300": "#e5edf5",
      "base-content": "#061b31",
      "success": "#15be53",
      "warning": "#9b6829",
      "error": "#ea2261"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "supabase": {
    "id": "supabase",
    "name": "Realtime Green",
    "category": "Backend & Data",
    "scale": {
      "density": 1.28,
      "radius": 0.67,
      "typeScale": 0.96,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#3ecf8e",
      "secondary": "#898989",
      "neutral": "#fafafa",
      "base-100": "#171717",
      "base-200": "#1c1c1c",
      "base-300": "#2e2e2e",
      "base-content": "#fafafa",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": true,
    "rhythm": 32
  },
  "superhuman": {
    "id": "superhuman",
    "name": "Inbox Zero",
    "category": "Developer Tools",
    "scale": {
      "density": 0.8,
      "radius": 0.67,
      "typeScale": 0.85,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#cbb7fb",
      "secondary": "#6f6c69",
      "neutral": "#292827",
      "base-100": "#ffffff",
      "base-200": "#ffffff",
      "base-300": "#dcd7d3",
      "base-content": "#292827",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 20
  },
  "tesla": {
    "id": "tesla",
    "name": "Electric",
    "category": "Automotive",
    "scale": {
      "density": 1.2,
      "radius": 1,
      "typeScale": 0.61,
      "motion": 1.5,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Anton",
      "body": "Inter"
    },
    "colors": {
      "primary": "#3e6ae1",
      "secondary": "#5c5e62",
      "neutral": "#171a20",
      "base-100": "#ffffff",
      "base-200": "#f4f4f4",
      "base-300": "#d0d1d2",
      "base-content": "#171a20",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 30
  },
  "tetris": {
    "id": "tetris",
    "name": "Blockfall",
    "category": "Themed & Unique",
    "scale": {
      "density": 0.8,
      "radius": 0,
      "typeScale": 0.85,
      "motion": 0.64,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Archivo Black",
      "body": "Inter"
    },
    "colors": {
      "primary": "#00f0f0",
      "secondary": "#94a3b8",
      "neutral": "#f8fafc",
      "base-100": "#050816",
      "base-200": "#10162a",
      "base-300": "#26324f",
      "base-content": "#f8fafc",
      "success": "#00f000",
      "warning": "#f0f000",
      "error": "#f00000"
    },
    "atmosphere": true,
    "rhythm": 20
  },
  "theverge": {
    "id": "theverge",
    "name": "Newsroom",
    "category": "Media & Consumer",
    "scale": {
      "density": 0.88,
      "radius": 0.67,
      "typeScale": 1.28,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#ff00a8",
      "secondary": "#9ca3af",
      "neutral": "#ffffff",
      "base-100": "#050505",
      "base-200": "#111111",
      "base-300": "#2b2b2b",
      "base-content": "#ffffff",
      "success": "#22c55e",
      "warning": "#facc15",
      "error": "#ef4444"
    },
    "atmosphere": true,
    "rhythm": 22
  },
  "together-ai": {
    "id": "together-ai",
    "name": "Cluster",
    "category": "AI & LLM",
    "scale": {
      "density": 0.8,
      "radius": 0.67,
      "typeScale": 0.85,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#010120",
      "secondary": "#666666",
      "neutral": "#000000",
      "base-100": "#ffffff",
      "base-200": "#ffffff",
      "base-300": "#ebebeb",
      "base-content": "#000000",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 20
  },
  "trading-terminal": {
    "id": "trading-terminal",
    "name": "Trading Terminal",
    "category": "Themed & Unique",
    "scale": {
      "density": 0.8,
      "radius": 0.67,
      "typeScale": 0.85,
      "motion": 0.73,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#38bdf8",
      "secondary": "#8492a6",
      "neutral": "#f8fafc",
      "base-100": "#070b12",
      "base-200": "#101826",
      "base-300": "#263246",
      "base-content": "#f8fafc",
      "success": "#22c55e",
      "warning": "#f59e0b",
      "error": "#ef4444"
    },
    "atmosphere": true,
    "rhythm": 20
  },
  "uber": {
    "id": "uber",
    "name": "Dispatch",
    "category": "Media & Consumer",
    "scale": {
      "density": 0.8,
      "radius": 0.67,
      "typeScale": 0.69,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#000000",
      "secondary": "#4b4b4b",
      "neutral": "#000000",
      "base-100": "#ffffff",
      "base-200": "#ffffff",
      "base-300": "#000000",
      "base-content": "#000000",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 20
  },
  "urdu": {
    "id": "urdu",
    "name": "Nastaliq",
    "category": "Editorial / Personal / Publication",
    "scale": {
      "density": 0.96,
      "radius": 1.33,
      "typeScale": 1.01,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Lora",
      "body": "Inter"
    },
    "colors": {
      "primary": "#1f8f46",
      "secondary": "#6b7d70",
      "neutral": "#15261a",
      "base-100": "#f3faf4",
      "base-200": "#ffffff",
      "base-300": "#d4e3d7",
      "base-content": "#15261a",
      "success": "#16a34a",
      "warning": "#d97706",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "vercel": {
    "id": "vercel",
    "name": "Edge Black",
    "category": "Developer Tools",
    "scale": {
      "density": 0.96,
      "radius": 0.67,
      "typeScale": 0.64,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#0070f3",
      "secondary": "#666666",
      "neutral": "#171717",
      "base-100": "#ffffff",
      "base-200": "#ffffff",
      "base-300": "rgba(0, 0, 0, 0.08)",
      "base-content": "#171717",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "vodafone": {
    "id": "vodafone",
    "name": "Signal",
    "category": "Media & Consumer",
    "scale": {
      "density": 0.96,
      "radius": 1.33,
      "typeScale": 0.9,
      "motion": 1,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#e60000",
      "secondary": "#6f7375",
      "neutral": "#1f1f1f",
      "base-100": "#ffffff",
      "base-200": "#f4f4f4",
      "base-300": "#d8d8d8",
      "base-content": "#1f1f1f",
      "success": "#008a00",
      "warning": "#f5b400",
      "error": "#bd0000"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "voltagent": {
    "id": "voltagent",
    "name": "Voltagent",
    "category": "AI & LLM",
    "scale": {
      "density": 0.96,
      "radius": 1,
      "typeScale": 0.91,
      "motion": 0.95,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#7cff6b",
      "secondary": "#8ba493",
      "neutral": "#f4fff8",
      "base-100": "#07110c",
      "base-200": "#101c16",
      "base-300": "#254132",
      "base-content": "#f4fff8",
      "success": "#52e875",
      "warning": "#facc15",
      "error": "#fb7185"
    },
    "atmosphere": true,
    "rhythm": 24
  },
  "warp": {
    "id": "warp",
    "name": "Terminal Warp",
    "category": "Developer Tools",
    "scale": {
      "density": 1.2,
      "radius": 1,
      "typeScale": 0.95,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#353534",
      "secondary": "#868584",
      "neutral": "#faf9f6",
      "base-100": "#161412",
      "base-200": "#1f1d1b",
      "base-300": "rgba(226, 226, 226, 0.35)",
      "base-content": "#faf9f6",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": true,
    "rhythm": 30
  },
  "webex": {
    "id": "webex",
    "name": "Meeting Room",
    "category": "Productivity & SaaS",
    "scale": {
      "density": 0.96,
      "radius": 1.5,
      "typeScale": 0.8,
      "motion": 1.09,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#00a3a6",
      "secondary": "#64748b",
      "neutral": "#0f172a",
      "base-100": "#f6f8fb",
      "base-200": "#ffffff",
      "base-300": "#dbe4ee",
      "base-content": "#0f172a",
      "success": "#22c55e",
      "warning": "#f59e0b",
      "error": "#e11d48"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "webflow": {
    "id": "webflow",
    "name": "Sitecraft",
    "category": "Design & Creative",
    "scale": {
      "density": 0.96,
      "radius": 0.33,
      "typeScale": 1.06,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#146ef5",
      "secondary": "#5a5a5a",
      "neutral": "#080808",
      "base-100": "#ffffff",
      "base-200": "#ffffff",
      "base-300": "#d8d8d8",
      "base-content": "#080808",
      "success": "#00d722",
      "warning": "#ffae13",
      "error": "#ee1d36"
    },
    "atmosphere": false,
    "rhythm": 24
  },
  "wechat": {
    "id": "wechat",
    "name": "Messenger Green",
    "category": "Social & Messaging",
    "scale": {
      "density": 0.72,
      "radius": 0.67,
      "typeScale": 0.68,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#07c160",
      "secondary": "#888888",
      "neutral": "#1a1a1a",
      "base-100": "#ededed",
      "base-200": "#f7f7f7",
      "base-300": "#e0e0e0",
      "base-content": "#1a1a1a",
      "success": "#07c160",
      "warning": "#fab702",
      "error": "#fa5151"
    },
    "atmosphere": false,
    "rhythm": 18
  },
  "wired": {
    "id": "wired",
    "name": "Feature Story",
    "category": "Media & Consumer",
    "scale": {
      "density": 0.88,
      "radius": 0,
      "typeScale": 1.2,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Archivo Black",
      "body": "Inter"
    },
    "colors": {
      "primary": "#e10600",
      "secondary": "#666666",
      "neutral": "#000000",
      "base-100": "#ffffff",
      "base-200": "#f2f2f2",
      "base-300": "#d0d0d0",
      "base-content": "#000000",
      "success": "#0f8a3b",
      "warning": "#f5a400",
      "error": "#c40000"
    },
    "atmosphere": false,
    "rhythm": 22
  },
  "wise": {
    "id": "wise",
    "name": "Transfer Green",
    "category": "Fintech & Crypto",
    "scale": {
      "density": 0.8,
      "radius": 2.5,
      "typeScale": 1.13,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#9fe870",
      "secondary": "#868685",
      "neutral": "#0e0f0c",
      "base-100": "#ffffff",
      "base-200": "#e8ebe6",
      "base-300": "rgba(14, 15, 12, 0.12)",
      "base-content": "#0e0f0c",
      "success": "#054d28",
      "warning": "#ffd11a",
      "error": "#d03238"
    },
    "atmosphere": false,
    "rhythm": 20
  },
  "x-ai": {
    "id": "x-ai",
    "name": "Monolith",
    "category": "AI & LLM",
    "scale": {
      "density": 0.96,
      "radius": 0,
      "typeScale": 0.85,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Space Grotesk",
      "body": "Inter"
    },
    "colors": {
      "primary": "#ffffff",
      "secondary": "rgba(255, 255, 255, 0.5)",
      "neutral": "#ffffff",
      "base-100": "#1f2228",
      "base-200": "rgba(255, 255, 255, 0.03)",
      "base-300": "rgba(255, 255, 255, 0.1)",
      "base-content": "#ffffff",
      "success": "#16a34a",
      "warning": "#eab308",
      "error": "#dc2626"
    },
    "atmosphere": true,
    "rhythm": 24
  },
  "xiaohongshu": {
    "id": "xiaohongshu",
    "name": "Little Red",
    "category": "Media & Consumer",
    "scale": {
      "density": 0.64,
      "radius": 1,
      "typeScale": 0.6,
      "motion": 0.91,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#ff2442",
      "secondary": "rgba(0, 0, 0, 0.45)",
      "neutral": "rgba(0, 0, 0, 0.8)",
      "base-100": "#f5f5f5",
      "base-200": "#ffffff",
      "base-300": "rgba(0, 0, 0, 0.08)",
      "base-content": "rgba(0, 0, 0, 0.8)",
      "success": "#02b940",
      "warning": "#ff7d03",
      "error": "#ff2442"
    },
    "atmosphere": false,
    "rhythm": 16
  },
  "zapier": {
    "id": "zapier",
    "name": "Automation",
    "category": "Productivity & SaaS",
    "scale": {
      "density": 0.96,
      "radius": 1,
      "typeScale": 0.96,
      "motion": 1,
      "choreography": "subtle",
      "smoothScroll": false
    },
    "fonts": {
      "display": "Inter",
      "body": "Inter"
    },
    "colors": {
      "primary": "#ff4f00",
      "secondary": "#7c6f64",
      "neutral": "#2d2a26",
      "base-100": "#fff7ed",
      "base-200": "#ffffff",
      "base-300": "#eadfd3",
      "base-content": "#2d2a26",
      "success": "#15803d",
      "warning": "#d97706",
      "error": "#dc2626"
    },
    "atmosphere": false,
    "rhythm": 24
  },
}

export const DESIGN_SYSTEM_IDS = Object.keys(DESIGN_SYSTEMS)
