/**
 * `<style>` → node styles, so an imported design arrives with its DESIGN.
 *
 * `import-html.ts` gives a correctly structured, fully editable, completely
 * UNSTYLED document: it maps tags to primitives and inline `style=""` to node
 * styles, and lists `style` among the tags it skips. Every design generated by
 * an agent — and every hand-written template worth importing — puts its CSS in
 * one `<style>` block and hangs it off class names, so ~4KB of styling per page
 * was being dropped on the floor. The class names were already retained on the
 * nodes; only the rules behind them were missing.
 *
 * ── Which selectors, and why only these ──────────────────────────────────────
 * Measured against 106 real templates rather than guessed. The selector
 * population is:
 *
 *     878  .a .b   descendant       853  .class          202  tag
 *     197  ::pseudo                 128  other (*, +)     95  .a.b
 *      80  @keyframes                25  :root            24  @media
 *      21  .a > b
 *
 * The four handled here — class, descendant, tag and `:root` — are ~78% of all
 * selectors and close to 100% of the ones that carry layout and colour. The
 * rest are deliberately NOT silently dropped: pseudo-elements, keyframes and
 * anything with a combinator this does not model are preserved verbatim as a
 * residual stylesheet on the page, so an import loses nothing visually even
 * where it cannot make something editable.
 *
 * ── Why not a real CSS engine ────────────────────────────────────────────────
 * A correct cascade needs the DOM, and this runs in a Worker with no DOM and a
 * hand-rolled tokenizer for exactly that reason. What it implements instead is
 * source order plus a crude specificity sort, which is what these stylesheets
 * actually rely on — they are single-author, single-file, and written flat.
 * Best-effort by design, like the HTML importer it extends.
 */

import type { Doc, Node } from "./schema"

export interface CssRule {
  /** Raw selector, one per rule (comma groups are split before this). */
  selector: string
  decls: Record<string, string>
  /** Breakpoint max-width in px, when the rule sat inside an @media. */
  maxWidth?: number
  /** Source order, for stable sorting. */
  order: number
}

export interface StylesheetParse {
  rules: CssRule[]
  /** `:root` custom properties — the design system's tokens. */
  rootVars: Record<string, string>
  /** Everything this module cannot model, kept verbatim rather than lost. */
  residual: string
}

const DECL_SPLIT = /;(?![^(]*\))/

function parseDecls(body: string): Record<string, string> {
  const out: Record<string, string> = {}
  for (const part of body.split(DECL_SPLIT)) {
    const i = part.indexOf(":")
    if (i < 0) continue
    const prop = part.slice(0, i).trim()
    const value = part.slice(i + 1).trim()
    if (prop && value) out[prop] = value
  }
  return out
}

/** Selectors this module can resolve against a node tree. */
function isModellable(sel: string): boolean {
  if (sel.startsWith("@") || sel.includes("::") || sel.includes(":")) return false
  if (/[>+~*[\]]/.test(sel)) return false
  return /^[.\w][\w.\s-]*$/.test(sel)
}

/**
 * Crude specificity: classes beat tags, more parts beat fewer. Enough to order
 * a single-author stylesheet correctly; not a substitute for the real algorithm.
 */
function specificity(sel: string): number {
  const parts = sel.trim().split(/\s+/)
  let score = 0
  for (const p of parts) score += (p.match(/\./g)?.length ?? 0) * 10 + (p.startsWith(".") ? 0 : 1)
  return score
}

export function parseStylesheet(css: string): StylesheetParse {
  const rules: CssRule[] = []
  const rootVars: Record<string, string> = {}
  const residual: string[] = []
  let order = 0

  // Strip comments first so a selector inside one cannot be matched.
  const clean = css.replace(/\/\*[\s\S]*?\*\//g, "")

  // Pull @media blocks out whole, record their contents against a breakpoint,
  // and leave the rest of the sheet to the flat pass below.
  const mediaRe = /@media([^{]+)\{((?:[^{}]*\{[^{}]*\}\s*)*)\}/g
  let m: RegExpExecArray | null
  const flat = clean.replace(mediaRe, (full, cond: string, body: string) => {
    const px = /max-width\s*:\s*(\d+)/.exec(cond)
    if (!px) {
      // min-width, print, prefers-* — not modelled, kept verbatim.
      residual.push(full)
      return ""
    }
    const maxWidth = Number(px[1])
    const inner = /([^{}]+)\{([^{}]*)\}/g
    let r: RegExpExecArray | null
    while ((r = inner.exec(body))) {
      for (const sel of r[1].split(",")) {
        const s = sel.trim()
        if (!s) continue
        if (isModellable(s)) {
          rules.push({ selector: s, decls: parseDecls(r[2]), maxWidth, order: order++ })
        } else {
          residual.push(`@media${cond}{${s}{${r[2]}}}`)
        }
      }
    }
    return ""
  })

  // @keyframes and any other at-rule: verbatim, never modelled.
  const atRe = /@(?:keyframes|supports|font-face|import)[^{]*\{(?:[^{}]*\{[^{}]*\}\s*)*\}|@import[^;]+;/g
  const flatNoAt = flat.replace(atRe, (full) => {
    residual.push(full)
    return ""
  })

  const ruleRe = /([^{}]+)\{([^{}]*)\}/g
  while ((m = ruleRe.exec(flatNoAt))) {
    const decls = parseDecls(m[2])
    for (const sel of m[1].split(",")) {
      const s = sel.trim()
      if (!s) continue
      if (s === ":root" || s === "html:root") {
        // Custom properties are the design system; plain declarations here are
        // page defaults and belong on the root node, not the token set.
        for (const [k, v] of Object.entries(decls)) {
          if (k.startsWith("--")) rootVars[k] = v
        }
        const nonVars = Object.entries(decls).filter(([k]) => !k.startsWith("--"))
        if (nonVars.length) {
          rules.push({ selector: "body", decls: Object.fromEntries(nonVars), order: order++ })
        }
        continue
      }
      if (isModellable(s)) {
        rules.push({ selector: s, decls, order: order++ })
      } else {
        residual.push(`${s}{${m[2]}}`)
      }
    }
  }

  return { rules, rootVars, residual: residual.join("\n") }
}

/** A node's own classes, as a set. */
function classSet(node: Node): Set<string> {
  return new Set((node.classes ?? "").split(/\s+/).filter(Boolean))
}

/**
 * Does `selector` match this node, given its ancestors?
 *
 * Descendant matching walks the ancestor chain right-to-left, which is how a
 * browser does it and is the only part of the cascade worth reproducing here.
 */
function matches(
  selector: string,
  nodeId: string,
  doc: Doc,
  parents: Map<string, string>,
  tags: Record<string, string>
): boolean {
  const parts = selector.trim().split(/\s+/).reverse()
  let currentId: string | undefined = nodeId

  for (let i = 0; i < parts.length; i++) {
    const part = parts[i]!
    let found = false
    while (currentId) {
      const node = doc.nodes[currentId]
      if (!node) break
      const ok = part.startsWith(".")
        ? part
            .split(".")
            .filter(Boolean)
            .every((c) => classSet(node).has(c))
        : tags[currentId] === part
      if (ok) {
        found = true
        // The leftmost part must match this exact node; ancestors may be any
        // distance above, so only the first step is anchored.
        currentId = parents.get(currentId)
        break
      }
      if (i === 0) return false // the subject itself must match
      currentId = parents.get(currentId)
    }
    if (!found) return false
  }
  return true
}

export interface ApplyResult {
  /** Nodes that gained at least one declaration. */
  styledNodes: number
  /** Declarations written across the document. */
  declarations: number
  /** Tokens lifted out of `:root`. */
  tokens: number
  /** CSS kept verbatim because it could not be modelled. */
  residual: string
}

/**
 * Resolve a stylesheet onto a Doc, in place.
 *
 * Existing inline styles win: `style=""` in the source is more specific than
 * any class rule, and the HTML importer has already put those on the node.
 */
export function applyStylesheetToDoc(
  doc: Doc,
  css: string,
  tags: Record<string, string>,
  breakpointIdForWidth: (px: number) => string | undefined
): ApplyResult {
  const { rules, rootVars, residual } = parseStylesheet(css)

  const parents = new Map<string, string>()
  for (const [id, node] of Object.entries(doc.nodes)) {
    for (const childId of node.children ?? []) parents.set(childId, id)
  }

  const ordered = [...rules].sort(
    (a, b) => specificity(a.selector) - specificity(b.selector) || a.order - b.order
  )

  let styledNodes = 0
  let declarations = 0
  const touched = new Set<string>()

  for (const nodeId of Object.keys(doc.nodes)) {
    const node = doc.nodes[nodeId]!
    const inline = { ...(node.style ?? {}) }

    for (const rule of ordered) {
      if (!matches(rule.selector, nodeId, doc, parents, tags)) continue

      if (rule.maxWidth != null) {
        const bp = breakpointIdForWidth(rule.maxWidth)
        if (!bp) continue
        const responsive = { ...(node.responsive ?? {}) }
        const slot = { ...(responsive[bp] ?? {}) }
        slot.style = { ...(slot.style ?? {}), ...rule.decls }
        responsive[bp] = slot
        node.responsive = responsive
        declarations += Object.keys(rule.decls).length
        touched.add(nodeId)
        continue
      }

      node.style = { ...(node.style ?? {}), ...rule.decls }
      declarations += Object.keys(rule.decls).length
      touched.add(nodeId)
    }

    // Re-apply the source's inline style last — it outranks every class rule.
    if (Object.keys(inline).length) node.style = { ...(node.style ?? {}), ...inline }
  }
  styledNodes = touched.size

  // `:root` custom properties are the imported design system's tokens.
  if (Object.keys(rootVars).length) {
    const colors: Record<string, string> = { ...(doc.theme?.colors ?? {}) }
    for (const [name, value] of Object.entries(rootVars)) {
      colors[name.replace(/^--/, "")] = value
    }
    doc.theme = { ...doc.theme, colors } as Doc["theme"]
  }

  return {
    styledNodes,
    declarations,
    tokens: Object.keys(rootVars).length,
    residual,
  }
}
